### ISSUE TITLE
More complete example how to run phpunit on an own extension

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/setup-shopware#2]
### Question

Can we provide a more complete example how to continue after the Shopware installation? Would we move the extension under test to to the `custom/` folder or composer require it ? What is the intended use?

**Comment by shyim** [comment]
does this example help?

 https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/blob/main/.github/workflows/unit.yml

**Comment by amenk** [comment]
Absolutely! Thanks :-) Might include it into the readme somehow?

**Comment by amenk** [comment]
We should add that to the readme.

PS: We managed also setting up for integration tests like this:

https://github.com/iMi-digital/shopware6-password-site/blob/develop/.github/workflows/php.yml

**Comment by shyim** [comment]
maybe we can add this installation step into this action with an optional input parameter 🤔.

**Comment by amenk** [comment]
That would be awesome

**Comment by amenk** [comment]
I saw that the phpunit bootstrap also seems to setup the test database automatically, so not sure how much of the installation we need here.

**Comment by shyim** [comment]
Yes, when you just want to run phpunit tests you don't need that. The TestBootstrapper will do everything. It makes still sense to have it for E2E testing

**Comment by shyim** [comment]
I adjusted some the README is that fine?
